export const Locations = [
  {
    name: 'Alberta',
    sites: [
      { name: 'Airdrie', subdomain: 'cityofairdrie' },
      { name: 'Camrose', subdomain: 'cityofcamrose' },
      { name: 'Grande Prairie', subdomain: 'cityofgrandeprairie' },
      { name: 'Lacombe', subdomain: 'cityoflacombe' },
      { name: 'Medicine Hat', subdomain: 'cityofmedicinehat' },
      { name: 'Strathmore', subdomain: 'strathmore' },
    ],
  },
  {
    name: 'British Columbia',
    sites: [
      { name: 'Abbortsford', subdomain: 'abbotsford' },
      { name: 'Campbell River', subdomain: 'campbellriver' },
      { name: 'Coquitlam', subdomain: 'cityofcoquitlam' },
      { name: 'Delta', subdomain: 'cityofdelta' },
      { name: 'Kamloops', subdomain: 'cityofkamloops' },
      { name: 'Maple Ridge', subdomain: 'cityofmapleridge' },
      { name: 'Mission', subdomain: 'cityofmission' },
      { name: 'Nanimo', subdomain: 'cityofnanaimo' },
      { name: 'New Westminster', subdomain: 'cityofnewwestminster' },
      { name: 'North Vancouver', subdomain: 'nvrc' },
      { name: 'Penticton', subdomain: 'cityofpenticton' },
      { name: 'Port Moody', subdomain: 'cityofportmoody' },
      { name: 'Prince George', subdomain: 'cityofprincegeorge' },
      { name: 'Richmond Oval', subdomain: 'richmondoval' },
      { name: 'Richmond', subdomain: 'richmondcity' },
      { name: 'Surrey', subdomain: 'cityofsurrey' },
      { name: 'Victoria', subdomain: 'cityofvictoria' },
      { name: 'White Rock', subdomain: 'cityofwhiterock' },
    ],
  },
  {
    name: 'Ontario',
    sites: [
      { name: 'Aurora', subdomain: 'cityofaurora' },
      { name: 'Belleville', subdomain: 'cityofbelleville' },
      { name: 'Brampton', subdomain: 'cityofbrampton' },
      { name: 'Burlington', subdomain: 'cityofburlington' },
      { name: 'Cornwall', subdomain: 'cityofcornwall' },
      { name: 'Guelph', subdomain: 'cityofguelph' },
      { name: 'Kawartha Lakes', subdomain: 'kawarthalakes' },
      { name: 'King', subdomain: 'townshipofking' },
      { name: 'Kingston', subdomain: 'cityofkingston' },
      { name: 'London', subdomain: 'cityoflondon' },
      { name: 'Markham', subdomain: 'cityofmarkham' },
      { name: 'Milton', subdomain: 'townofmilton' },
      { name: 'New Tecumseth', subdomain: 'townofnewtecumseth' },
      { name: 'Oakville', subdomain: 'townofoakville' },
      { name: 'Owen Sound', subdomain: 'cityofowensound,' },
      { name: 'Peterborough', subdomain: 'cityofpeterborough' },
      { name: 'Thunder Bay', subdomain: 'cityofthunderbay' },
      { name: 'Vaughn', subdomain: 'vaughan' },
      { name: 'Woodstock', subdomain: 'woodstock' },
    ],
  },
  {
    name: 'Rest of Canada',
    sites: [
      { name: 'Quispamsis, NB', subdomain: 'townofquispamsis' },
      { name: 'Martensville, SK', subdomain: 'cityofmartensville' },
      { name: 'Moose Jaw, SK', subdomain: 'cityofmoosejaw' },
      { name: 'Price Albert, SK', subdomain: 'citypa' },
      { name: 'Swift Current, SK', subdomain: 'cityofswiftcurrent' },
      { name: 'Weyburn, SK', subdomain: 'cityofweyburn' },
      { name: 'Yorkton, SK', subdomain: 'cityofyorkton' },
      { name: 'Whitehorse, YK', subdomain: 'whitehorse' },
    ],
  },
  {
    name: 'USA',
    sites: [
      { name: 'Peoria, AZ', subdomain: 'cityofpeoriaaz' },
      { name: 'Calistoga, CA', subdomain: 'cityofcalistoga' },
      { name: 'Eureka, CA', subdomain: 'cityofeureka' },
      { name: 'Coronado, CA', subdomain: 'cityofcoronado' },
      { name: 'Menlo Park, CA', subdomain: 'cityofmenlopark' },
      { name: 'Modesto, CA', subdomain: 'modesto' },
      { name: 'Oakland, CA', subdomain: 'cityofoakland' },
      { name: 'Rohnert Park, CA', subdomain: 'cityofrohnertpark' },
      { name: 'Rossland, CA', subdomain: 'cityofrossland' },
      { name: 'Santa Barbara, CA', subdomain: 'cityofsantabarbara' },
      { name: 'Walnut Creek, CA', subdomain: 'cityofwalnutcreek' },
      { name: 'Brandon, FL', subdomain: 'brandon' },
      { name: 'West Des Moines, IA', subdomain: 'cityofwestdesmoinesparksandrecreation' },
      { name: 'Albany, NY', subdomain: 'albanyparksandrecreation' },
      { name: 'Olivette, MO', subdomain: 'olivetteparksandrecdept' },
      { name: 'Saratoga, NY', subdomain: 'losgatos' },
      { name: 'Oklahoma City, OK', subdomain: 'oklahomacity' },
      { name: 'El Paso, TX', subdomain: 'cityofelpaso' },
      { name: 'Frisco, TX', subdomain: 'friscotexas' },
      { name: 'James City County, VA', subdomain: 'jamescitycountyparksandrec' },
      { name: 'Issaquah, WA', subdomain: 'cityofissaquah' },
      { name: 'Mercer Island, WA', subdomain: 'cityofmercerisland' },
      { name: 'Renton, WA', subdomain: 'cityofrenton' },
    ],
  },
  {
    name: 'Australia',
    sites: [{ name: 'Onkaparinga, SA', subdomain: 'onkaparinga' }],
  },
];
