export const Locations = [
  {
    name: 'Alberta',
    sites: [
      { name: 'Airdrie', subdomain: 'cityofairdrie' },
      { name: 'Camrose', subdomain: 'cityofcamrose' },
      { name: 'Cochrane', subdomain: 'cochrane' },
      { name: 'Cold Lake', subdomain: 'cityofcoldlake' },
      { name: 'Dawson Creek', subdomain: 'cityofdawsoncreek' },
      { name: 'Grande Prairie', subdomain: 'cityofgrandeprairie' },
      { name: 'Lacombe', subdomain: 'cityoflacombe' },
      { name: 'Medicine Hat', subdomain: 'cityofmedicinehat' },
      { name: 'Red Deer', subdomain: 'reddeerpolytech' },
      { name: 'Strathmore', subdomain: 'strathmore' },
    ],
  },
  {
    name: 'British Columbia',
    sites: [
      { name: 'Abbotsford', subdomain: 'abbotsford' },
      { name: 'Campbell River', subdomain: 'campbellriver' },
      { name: 'Comox Valley', subdomain: 'comoxvalley' },
      { name: 'Coquitlam', subdomain: 'cityofcoquitlam' },
      { name: 'Cranbrook', subdomain: 'cityofcranbrook' },
      { name: 'Cumberland', subdomain: 'cumberland' },
      { name: 'Delta', subdomain: 'cityofdelta' },
      { name: 'Kamloops', subdomain: 'cityofkamloops' },
      { name: 'Maple Ridge', subdomain: 'cityofmapleridge' },
      { name: 'Mission', subdomain: 'cityofmission' },
      { name: 'Nanaimo', subdomain: 'cityofnanaimo' },
      { name: 'New Westminster', subdomain: 'cityofnewwestminster' },
      { name: 'North Vancouver', subdomain: 'nvrc' },
      { name: 'Oak Bay', subdomain: 'oakbayrec' },
      { name: 'Pemberton', subdomain: 'pemberton' },
      { name: 'Penticton', subdomain: 'cityofpenticton' },
      { name: 'Port Alberni', subdomain: 'portalberni' },
      { name: 'Port Moody', subdomain: 'cityofportmoody' },
      { name: 'Prince George', subdomain: 'cityofprincegeorge' },
      { name: 'Richmond Oval', subdomain: 'richmondoval' },
      { name: 'Richmond', subdomain: 'richmondcity' },
      { name: 'Summerland', subdomain: 'summerland' },
      { name: 'Surrey', subdomain: 'cityofsurrey' },
      { name: 'Victoria', subdomain: 'cityofvictoria' },
      { name: 'White Rock', subdomain: 'cityofwhiterock' },
      { name: 'Williams Lake', subdomain: 'cityofwilliamslake' },
    ],
  },
  {
    name: 'Ontario',
    sites: [
      { name: 'Aurora', subdomain: 'cityofaurora' },
      { name: 'Belleville', subdomain: 'cityofbelleville' },
      { name: 'Brampton', subdomain: 'cityofbrampton' },
      { name: 'Burlington', subdomain: 'cityofburlington' },
      { name: 'Cornwall', subdomain: 'cityofcornwall' },
      { name: 'Greater Sudbury', subdomain: 'cityofgreatersudbury' },
      { name: 'Guelph', subdomain: 'cityofguelph' },
      { name: 'Halton Hills', subdomain: 'haltonhills' },
      { name: 'Kawartha Lakes', subdomain: 'kawarthalakes' },
      { name: 'King', subdomain: 'townshipofking' },
      { name: 'Kingston', subdomain: 'cityofkingston' },
      { name: 'London', subdomain: 'cityoflondon' },
      { name: 'Markham', subdomain: 'cityofmarkham' },
      { name: 'Milton', subdomain: 'townofmilton' },
      { name: 'New Tecumseth', subdomain: 'townofnewtecumseth' },
      { name: 'Norfolk County', subdomain: 'norfolkcounty' },
      { name: 'Oakville', subdomain: 'townofoakville' },
      { name: 'Owen Sound', subdomain: 'cityofowensound' },
      { name: 'Peterborough', subdomain: 'cityofpeterborough' },
      { name: 'Sarnia', subdomain: 'sarnia' },
      { name: 'Stratford', subdomain: 'stratfordcanada' },
      { name: 'Thunder Bay', subdomain: 'cityofthunderbay' },
      { name: 'Vaughn', subdomain: 'vaughan' },
      { name: 'Woodstock', subdomain: 'woodstock' },
    ],
  },
  {
    name: 'Rest of Canada',
    sites: [
      { name: 'Steinbach, MB', subdomain: 'steinbach' },
      { name: 'Martensville, SK', subdomain: 'cityofmartensville' },
      { name: 'Melfort, SK', subdomain: 'cityofmelfort' },
      { name: 'Moose Jaw, SK', subdomain: 'cityofmoosejaw' },
      { name: 'Prince Albert, SK', subdomain: 'citypa' },
      { name: 'Quispamsis, NB', subdomain: 'townofquispamsis' },
      { name: 'Swift Current, SK', subdomain: 'cityofswiftcurrent' },
      { name: 'Warman, SK', subdomain: 'cityofwarman' },
      { name: 'Weyburn, SK', subdomain: 'cityofweyburn' },
      { name: 'Yorkton, SK', subdomain: 'cityofyorkton' },
      { name: 'Whitehorse, YK', subdomain: 'whitehorse' },
    ],
  },
  {
    name: 'California',
    sites: [
      { name: 'Calistoga', subdomain: 'cityofcalistoga' },
      { name: 'Eureka', subdomain: 'cityofeureka' },
      { name: 'Menlo Park', subdomain: 'cityofmenlopark' },
      { name: 'Mill Valley', subdomain: 'cityofmillvalley' },
      { name: 'Mission Viejo', subdomain: 'missionviejo' },
      { name: 'Modesto', subdomain: 'modesto' },
      { name: 'Oakland', subdomain: 'cityofoakland' },
      { name: 'Patterson', subdomain: 'patterson' },
      { name: 'Pleasanton', subdomain: 'cityofpleasanton' },
      { name: 'Rohnert Park', subdomain: 'cityofrohnertpark' },
      { name: 'Roseville', subdomain: 'cityofroseville' },
      { name: 'Rossland', subdomain: 'cityofrossland' },
      { name: 'San Rafael', subdomain: 'cityofsanrafael' },
      { name: 'Santa Barbara', subdomain: 'cityofsantabarbara' },
      { name: 'Sausalito', subdomain: 'cityofsausalito' },
      { name: 'Walnut Creek', subdomain: 'cityofwalnutcreek' },
    ],
  },
  {
    name: 'Texas',
    sites: [
      { name: 'Amarillo', subdomain: 'cityofamarilloparksandrec' },
      { name: 'El Paso', subdomain: 'cityofelpaso' },
      { name: 'Frisco', subdomain: 'friscotexas' },
      { name: 'Georgetown', subdomain: 'georgetownparks' },
      { name: 'Pearland', subdomain: 'pearlandparksandrec' },
    ],
  },
  {
    name: 'Washington',
    sites: [
      { name: 'Issaquah', subdomain: 'cityofissaquah' },
      { name: 'Lynnwood', subdomain: 'cityoflynnwood' },
      { name: 'Maple Valley', subdomain: 'cityofmaplevalley' },
      { name: 'Mercer Island', subdomain: 'cityofmercerisland' },
      { name: 'Renton', subdomain: 'cityofrenton' },
      { name: 'Sammamish', subdomain: 'cityofsammamish' },
      { name: 'Tukwila', subdomain: 'tukwilaparks' },
    ],
  },
  {
    name: 'USA',
    sites: [
      { name: 'Peoria, AZ', subdomain: 'cityofpeoriaaz' },
      { name: 'Brandon, FL', subdomain: 'brandon' },
      { name: 'Sugar Hill, GA', subdomain: 'cityofsugarhill' },
      { name: 'West Des Moines, IA', subdomain: 'cityofwestdesmoinesparksandrecreation' },
      { name: 'Southgate, MI', subdomain: 'southgate' },
      { name: 'Wright County, MN', subdomain: 'wrightcountyparksandrec' },
      { name: 'Olivette, MO', subdomain: 'olivetteparksandrecdept' },
      { name: 'Albany, NY', subdomain: 'albanyparksandrecreation' },
      { name: 'Saratoga, NY', subdomain: 'losgatos' },
      { name: 'Oklahoma City, OK', subdomain: 'oklahomacity' },
      { name: 'Medford, OR', subdomain: 'cityofmedford' },
      { name: 'James City County, VA', subdomain: 'jamescitycountyparksandrec' },
    ],
  },
  {
    name: 'Australia',
    sites: [{ name: 'Onkaparinga, SA', subdomain: 'onkaparinga' }],
  },
];
